# Generated by Django 3.2.5 on 2022-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voterID',
        ),
        migrations.AddField(
            model_name='voter',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='ward',
            field=models.CharField(blank=True, choices=[('Ward1', 'Ward1'), ('Ward2', 'Ward2'), ('Ward3', 'Ward3'), ('Ward4', 'Ward4')], default='Unknown', max_length=20, null=True),
        ),
    ]
