# Generated by Django 3.2.5 on 2022-10-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221016_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
