# Generated by Django 3.2.5 on 2022-10-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_voter_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
