# Generated by Django 3.2.8 on 2022-10-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_voter_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
