# Generated by Django 3.2.8 on 2022-10-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_voter_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='votedTo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
