# Generated by Django 3.2.8 on 2022-10-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_voter_votedto'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candiname', models.CharField(max_length=45)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('ward', models.CharField(blank=True, choices=[('Ward1', 'Ward1'), ('Ward2', 'Ward2'), ('Ward3', 'Ward3'), ('Ward4', 'Ward4')], default='Unknown', max_length=45, null=True)),
            ],
        ),
    ]
