# Generated by Django 3.2.8 on 2022-10-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='candidateLogo/'),
        ),
    ]
