# Generated by Django 3.2.8 on 2022-10-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_candidate_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='voterImgs/'),
        ),
    ]
