# Generated by Django 3.2.8 on 2022-10-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_voter_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='dp',
            field=models.ImageField(blank=True, default='voterImgs/default.png', null=True, upload_to='voterImgs/'),
        ),
    ]
